### ISSUE TITLE
Preparing the code as a package

### ISSUE THREAD

**Issue by ngraymon** [ngraymon/termfactory#35]
writing a setup.cfg, all that other stuff
probably a good experience for @lhprice and he can look at Pibronic as an example

this is the stuff that makes `pip install resid-build` work!

For testing purposes you can do `pip install -e resid-build`

**Comment by lhprice** [comment]
some of setup.py just needs some housekeeping for version numbers etc but we now have a pilot version of the package.

https://pypi.org/project/termfactory/

**Comment by ngraymon** [comment]
- [ ] Rebase `prepare_package` onto latest master branch
- [ ] pull request `explanatory_readme` into `prepare_package` 
- [ ] pull request ``prepare_package` into `master`

**Comment by ngraymon** [comment]
Agreed
